### ISSUE TITLE
autoupdate errors with docpad 5.x

### ISSUE THREAD

**Issue by wenzowski** [docpad-archive/extras#1]
#### Using the [autoupdate plugin](https://github.com/bevry/docpad-extras/tree/docpad-5.x/plugins/autoupdate) results in errors.

See the following stack trace from a `$ docpad run`

```
warning: Failed to load the plugin docpad-plugin-autoupdate at /code/canvas.docpad/node_modules/docpad-plugin-autoupdate. The error follows
warning: An error occured: Cannot find module 'now' Error: Cannot find module 'now'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at new AutoUpdatePlugin (/code/canvas.docpad/node_modules/docpad-plugin-autoupdate/autoupdate.plugin.coffee:17:20)
    at PluginLoader.create (/usr/local/lib/node_modules/docpad/lib/plugin-loader.coffee:169:26)
    at /usr/local/lib/node_modules/docpad/lib/docpad.coffee:812:31
    at PluginLoader.load (/usr/local/lib/node_modules/docpad/lib/plugin-loader.coffee:150:11)
    at /usr/local/lib/node_modules/docpad/lib/docpad.coffee:808:29
    at /usr/local/lib/node_modules/docpad/lib/plugin-loader.coffee:136:47
info: Welcome to DocPad v5.0.4
info: Didn't place the skeleton as the desired structure already exists
info: Generating...
error: An error occured: Cannot read property 'docpadSync' of undefined TypeError: Cannot read property 'docpadSync' of undefined
    at AutoUpdatePlugin.writeAfter (/code/canvas.docpad/node_modules/docpad-plugin-autoupdate/autoupdate.plugin.coffee:49:21)
    at /usr/local/lib/node_modules/docpad/lib/plugin.coffee:44:34
    at /usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/events.coffee:273:18
    at _Class.nextTask (/usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.coffee:96:11)
    at _Class.complete (/usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.coffee:115:20)
    at /usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.coffee:127:33
    at CachrPlugin.writeAfter (/code/canvas.docpad/node_modules/docpad-plugin-cachr/cachr.plugin.coffee:118:47)
    at /usr/local/lib/node_modules/docpad/lib/plugin.coffee:44:34
    at /usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/events.coffee:273:18
    at _Class.run (/usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.coffee:171:15)
```

Got latest versions via npm with `npm update docpad -g` for cmd line and `npm update` for `package.json` app dependencies.
#### Dependencies from `package.json`

```
"dependencies": {
    "coffee-script": "1.3.x",
    "express": "2.5.x",
    "docpad": "5.0.x",
    "docpad-plugin-autoupdate": "latest",
    "docpad-plugin-coffee": "latest",
    "docpad-plugin-eco": "latest",
    "docpad-plugin-haml": "latest",
    "docpad-plugin-hogan": "latest",
    "docpad-plugin-jade": "latest",
    "docpad-plugin-less": "latest",
    "docpad-plugin-markdown": "latest",
    "docpad-plugin-stylus": "latest",
    "docpad-plugin-sass": "latest",
    "docpad-plugin-cachr": "latest",
    "docpad-plugin-cleanurls": "latest",
    "docpad-plugin-feedr": "latest",
    "docpad-plugin-partials": "latest",
    "docpad-plugin-related": "latest"
},
```

Except for the obvious `info: Welcome to DocPad v5.0.5`, identical results.

Great app, thanks for all your hard work!

**Comment by balupton** [comment]
Thanks mate, yeah this plugin was written for one of the first versions of DocPad and is need for a desperate upgrade. I've found that `cmd+r` and the growl notifications do a pretty good replacement...

Would you like to give it a crack at getting it to work again? You can `docpad run -d` for debug info. Ideally, it should be moved from [NowJS](http://nowjs.com/) to [Socket.io](http://socket.io/) - as NowJS is huge overkill.

**Comment by wenzowski** [comment]
I haven't played with Socket.io yet, nor extensively with node for that matter. Code likely to be rough, but I'll give it a shot when I have the time.

**Comment by balupton** [comment]
closing due to age
