### ISSUE TITLE
Using partials within partials

### ISSUE THREAD

**Issue by santip** [docpad-archive/extras#3]
if I try to include a partial from a partial it fails with the error:

```
error: An error occured: Object #<Object> has no method 'partial' TypeError: Object #<Object> has no method 'partial'
    at Object.<anonymous> (eval at <anonymous> (/Users/santip/newttt/node_modules/docpad-plugin-eco/node_modules/eco/lib/compiler.js:19:12))
    at Object.<anonymous> (eval at <anonymous> (/Users/santip/newttt/node_modules/docpad-plugin-eco/node_modules/eco/lib/compiler.js:19:12))
    at eval at <anonymous> (/Users/santip/newttt/node_modules/docpad-plugin-eco/node_modules/eco/lib/compiler.js:19:12)
    at Function.render (/Users/santip/newttt/node_modules/docpad-plugin-eco/node_modules/eco/lib/index.js:26:24)
    at EcoPlugin.render (/Users/santip/newttt/node_modules/docpad-plugin-eco/eco.plugin.coffee:26:30)
    at /usr/local/lib/node_modules/docpad/lib/plugin.js:45:34
    at /usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/events.js:274:18
    at _Class.nextTask (/usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.js:97:11)
    at _Class.complete (/usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.js:116:20)
    at /usr/local/lib/node_modules/docpad/node_modules/bal-util/lib/flow.js:128:33[22m
```

I tried passing in { partial: @partial } as templateData to workaround the limitation and it removes the error message but the inner partial is not included.

**Comment by santip** [comment]
actually, the { partial: @partial } does work

still, it would be nice not needing to do this hack and have @partial always available within partials

**Comment by balupton** [comment]
closing due to age
