### ISSUE TITLE
issue with twitter json feedr module - fix included

### ISSUE THREAD

**Issue by madshobye** [docpad-archive/extras#5]
Got this: Unexpected token : SyntaxError: Unexpected token :
when pulling this:

twit3:
                    url: "http://search.twitter.com/search.json?q=asd"

Solved it by adding replace to line 81 feedr.plugin.coffee:
# Parse the requested data

```
                body = body.replace("   "," ")
```

Read here that tab causes problems in chrome - replaced tabs with space. Might be a bad fix, but it is at least a starting point to understand the problem.

http://stackoverflow.com/questions/3143698/uncaught-syntaxerror-unexpected-token

Full error below:

An error occured: Unexpected token : SyntaxError: Unexpected token :
    at Request._callback (/Users/madshobye/Dropbox/nodeLive/hobyedk_docpad5/node_modules/docpad-plugin-feedr/feedr.plugin.coffee:81:29)
    at Request.callback (/Users/madshobye/Dropbox/nodeLive/hobyedk_docpad5/node_modules/docpad-plugin-feedr/node_modules/request/main.js:119:22)
    at Request.<anonymous> (native)
    at Request.emit (events.js:70:17)
    at Request.<anonymous> (/Users/madshobye/Dropbox/nodeLive/hobyedk_docpad5/node_modules/docpad-plugin-feedr/node_modules/request/main.js:521:16)
    at Request.emit (events.js:67:17)
    at IncomingMessage.<anonymous> (/Users/madshobye/Dropbox/nodeLive/hobyedk_docpad5/node_modules/docpad-plugin-feedr/node_modules/request/main.js:483:14)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at Socket.ondata (http.js:1147:24)

**Comment by madshobye** [comment]
Hmm I am wrong the replace did not solve the problem and as an afterthought this is not a good solution = pretty bad hack. The issue still stands :) I solved it by using an atom feed instead.

**Comment by balupton** [comment]
Yeah most likely the data that is returned is invalid. Not really sure what to do about that besides using a different feed format.

**Comment by balupton** [comment]
closing due to age
